### ISSUE TITLE
System.NotSupportedException: Unable to activate instance of type AiForms.Dialogs.LoadingDialogPayload

### ISSUE THREAD

**Issue by iamheiner** [muak/AiForms.Dialogs#17]
### Description
Appcenter reports many crashes on device: (HUAWEI Y5 2018):

### Xamarin Exception Stack:
System.NotSupportedException: Unable to activate instance of type AiForms.Dialogs.LoadingDialogPayload from native handle 0x71 (key_handle 0x5376c9e).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017e] in <046df5261d3b4963948bfc5b13b956f1>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in <046df5261d3b4963948bfc5b13b956f1>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <046df5261d3b4963948bfc5b13b956f1>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <046df5261d3b4963948bfc5b13b956f1>:0
  at Android.OS.Bundle.GetSerializable (System.String key) [0x0003d] in <046df5261d3b4963948bfc5b13b956f1>:0
  at AiForms.Dialogs.LoadingPlatformDialog.OnCreateDialog (Android.OS.Bundle savedInstanceState) [0x0000e] in <4da79d9d1b6649a0bc3d61fc47db493c>:0
  at Android.App.DialogFragment.n_OnCreateDialog_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <046df5261d3b4963948bfc5b13b956f1>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.20(intptr,intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for AiForms.Dialogs.LoadingDialogPayload::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x000b5] in <046df5261d3b4963948bfc5b13b956f1>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <046df5261d3b4963948bfc5b13b956f1>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at crc64234e47a113e7c1a9.LoadingPlatformDialog.n_onCreateDialog(Native Method)
      at crc64234e47a113e7c1a9.LoadingPlatformDialog.onCreateDialog(LoadingPlatformDialog.java:31)
      at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:406)
      at android.app.Fragment.performGetLayoutInflater(Fragment.java:1325)
      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
      at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1619)
      at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3028)
      at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2980)
      at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
      at android.app.Activity.performCreate(Activity.java:7116)
      at android.app.Activity.performCreate(Activity.java:7101)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
      at android.app.ActivityThread.-wrap11(Unknown Source:0)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
      at android.os.Handler.dispatchMessage(Handler.java:106)
      at android.os.Looper.loop(Looper.java:166)
      at android.app.ActivityThread.main(ActivityThread.java:6861)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1554)
2   java.lang.Thread.getAllStackTraces(Thread.java:1604)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1137)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:58)
5   crc64234e47a113e7c1a9.LoadingPlatformDialog.n_onCreateDialog(LoadingPlatformDialog.java:-2)
6   crc64234e47a113e7c1a9.LoadingPlatformDialog.onCreateDialog(LoadingPlatformDialog.java:31)
7   android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:406)
8   android.app.Fragment.performGetLayoutInflater(Fragment.java:1325)
9   android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
10  android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
11  android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1619)
12  android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3028)
13  android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2980)
14  android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
15  android.app.Activity.performCreate(Activity.java:7116)
16  android.app.Activity.performCreate(Activity.java:7101)
17  android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
18  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2922)
19  android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
20  android.app.ActivityThread.-wrap11
21  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
22  android.os.Handler.dispatchMessage(Handler.java:106)
23  android.os.Looper.loop(Looper.java:166)
24  android.app.ActivityThread.main(ActivityThread.java:6861)
25  java.lang.reflect.Method.invoke(Method.java:-2)
26  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
27  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Thread 3124:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:780)

Thread 3125:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:780)

Thread 3126:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:380)
2   java.lang.Thread.sleep(Thread.java:321)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:342)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:364)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:281)
6   java.lang.Daemons$Daemon.run(Daemons.java:103)
7   java.lang.Thread.run(Thread.java:780)

Thread 3140:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2153)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
5   java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
6   java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:780)

Thread 3141:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:366)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 3143:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:366)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 3144:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:366)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 3145:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2153)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
5   java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
6   java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:780)

### Platforms

- [X] Android
- [ ] iOS

### Basic Information

- AiForms.Dialogs 1.0.7
- Xamarin.Forms 4.6.0
- Device: 
      Android: 8.1.0
      Android Build: HUAWEIDRA-LX3
      Manufacturer: HUAWEI
      Model: DRA-LX3

**Comment by muak** [comment]
I fixed this issue on version 1.0.13.
